### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ohler55/perfer#1]
I would like to point out that identifiers like “[`__PERFER_DROP_H__`](https://github.com/ohler55/perfer/blob/0cd65bf2a81813650e71c7069131ebcc69826856/src/drop.h#L3 "Update candidate")” and “[`_Pool`](https://github.com/ohler55/perfer/blob/628a58086a441d2a6d7e1bdedd6d68c32b619b71/src/pool.h#L11 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by ohler55** [comment]
The next target. :-)

I'll do the same cleanup here as in Agoo.

**Comment by ohler55** [comment]
Fixed in the latest push.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/ohler55/perfer/commit/7ff0673ef651d907c2d8c34d786e500908514c2b "Reserved identifier fix").

**Comment by ohler55** [comment]
Will you close this or would you like me to?
