### ISSUE TITLE
Simple usage example doesn't work

### ISSUE THREAD

**Issue by dalisoft** [ohler55/perfer#5]
Hi @ohler55 

Thanks for this tool.

But i think it's doesn't work right!

Command: `perfer -t2 -c2 -d2 http://localhost:4000`

Results:
```bash
➜  ~ perfer -t2 -c2 -d2 http://localhost:4000 
*-*-* Only one URL is allowed.

usage: perfer [options] <server-address>

Saturates a web server with HTTP requests while tracking the number of requests,
latency, and throughput. After the duration specified no more requests are sent
and the application terminates when all responses have been received or 10
seconds, which ever is sooner.

  -h                      This help page.
  --help

  -v                      Verbose mode.

  --version               Version of this application.

  -d <duration>           Duration in seconds for the run. Positive decimal
  --duration <duration>   values are accepted.

  -m <rate>               Set a metering rate in request per second.
  --meter <rate>          (default: 0, indicating no metering)

  -t <number>             Number of threads to use for sending requests and
  --threads <number>      receiving responses. (default: 1)

  -c <number>             Total number of connection to use for sending
  --connections <number>  requests (default: 1)

  -b <number>             Maximum backlog for pipeline on a connection.
  --backlog <number>      (default: 1, range 1 - 15)

  -l <percent,...>        Percentages of latency spread to report.
  --latency <percent,...> (example: 10,20,30,40,50,60,70,80,90,99)

  -g <wide>x<high>        Print a latency graph with the dimensions specified.
  --graph <wide>x<high>

  -r <file>               File with the full content of the HTTP request.
  --request <file>        The -keep-alive option is ignored.

  -k                      Keep connections alive instead of closing.
  --keep-alive

  -a <name: value>        Add an HTTP header field with name and value.
  --add <name: value>

  -p <content>            HTTP POST with the content provided.
  --post <content>        example: -p 'mutation { repeat(word: "Hello") }'

  -j                      JSON output.
  --json

  <url>                   URL for requests.
                          example: http://localhost:6464/index.html
```

Or i'm doing something wrong?

**Comment by ohler55** [comment]
Options need a space separating the key from the value so this would be the correct syntax.

`prefer -t 2 -c 2 -d 2 http://localhost:4000`

**Comment by dalisoft** [comment]
Thanks. I’d think it’s normalizes args, seems not. Nice tool

**Comment by dalisoft** [comment]
Duration parameter doesn't work as i'm giving `-d 2`, but it runs for 0.7 second. Or giving `-d 5, but it runs for 3.5 second`

Also, `wrk` works much accurate and shows real requests per second, but perfer shows very low values and it's impossible.

![](http://joxi.ru/KAxWB0XHZNeP32?d=1)

**Comment by ohler55** [comment]
Perfer attempts to run for the designated time. Usually it is closer than what you are seeing. There are a number of parameters you should try. By default wrk uses keep-alive. You must set the -k option of perfer for keep alive. You can also set the pipelining option -b to some value like 3 if you want.

**Comment by ohler55** [comment]
Did any of those suggestions help?

**Comment by dalisoft** [comment]
Yep, it helped. Thanks

**Comment by ohler55** [comment]
With the changes did you find prefer gave faster results or about the same?

**Comment by dalisoft** [comment]
Perfer doesn't gives faster results, i understand new things with perfer.
Perfer gives accurate results!

Nice tool, i recommend to others to understand, numbers on `wrk` isn't accurately

**Comment by ohler55** [comment]
I'm curious why you say wrk is not accurate.

**Comment by dalisoft** [comment]
Perfer shows really accurate results by creating new connection by default. 
This means, it shows real life example, not higher numbers. Because i really tried improve performance, knew about network delay, but didn’t know good about KeepAlive. On different users not single Connection, yes? I always wanted benchmark how much requests will my library handler at same time from different location, not from single location. 
I seem, my library does not differ much from express. Does not worth improving performance, because there TCP/Network layer...

**Comment by ohler55** [comment]
Both new connections and old are important. Once a connection is made there are many pages that must be retrieved. CSS, Javascript, HTML, and data. Keep-Alive lets this pages be downloaded faster.

Anyway, you have options. Thank you for the feedback.

**Comment by dalisoft** [comment]
Yep, i agree about keep alive, but my focus more connection handling at same time
